routes/web.php
<?php

use App\Http\Controllers\ticketController;
use App\Http\Controllers\categoriaController;
use App\Http\Controllers\UserSettingsController;
use App\Http\Controllers\usuarioController;
use App\Http\Controllers\roleController;
use App\Http\Controllers\reportesController;

use App\Http\Controllers\activoController;
use App\Http\Controllers\act_tipoController;
use App\Http\Controllers\act_funcionController;
use App\Http\Controllers\act_estadoController;
use App\Http\Controllers\reportesAController;


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// == HOME ==
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware('can:home')->name('home');

// == TICKET ==
Route::resource('ticket',ticketController::class)->names('ticket');
// == CATEGORIA ==
Route::resource('categoria',categoriaController::class)->names('categoria');
// == USUARIOS ==
Route::resource('usuario',usuarioController::class)->names('usuario');
// == ROLES ==
Route::resource('role',roleController::class)->names('role');
// == REPORTES ==
Route::resource('reportes',reportesController::class)->names('reportes');
// Ruta personalizada para TICKET PROCESAR
Route::post('ticket/procesar', [TicketController::class, 'procesar'])->name('ticket.procesar');


Auth::routes();
Route::get('/profile', [UserSettingsController::class, 'Profile'])->name('Profile')->middleware('auth');
Route::post('/change/profile', [UserSettingsController::class, 'changeProfile'])->name('changeProfile');


// == ACTIVOS ==
Route::resource('activo',activoController::class)->names('activo');
// == TIPOS ==
Route::resource('tipo',act_tipoController::class)->names('tipo');
// == FUNCIONES ==
Route::resource('funcion',act_funcionController::class)->names('funcion');
// == ESTADOS ==
Route::resource('estado',act_estadoController::class)->names('estado');
// == REPORTE ACTIVOS ==
Route::resource('reportesA',reportesAController::class)->names('reportesA');
// Ruta personalizada para ACTIVO PROCESAR
Route::post('activo/procesar', [activoController::class, 'procesar'])->name('activo.procesar');

resources/views/tipo/create.blade.php
@extends('adminlte::page')

@section('title', 'Nuevo Tipo de Equipo')


@section('content_header')
    <h1>Nuevo Tipo de Equipo</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">


        {!! Form::open(['route' => 'tipo.store','autocomplete' => 'off','files' => true]) !!}
        @include('tipo.partials.form')
        <table style="margin: 0; auto; width:100%">
            <tr>
                <td style="display: flex; justify-content: right;">
                    <div class="display: flex; justify-content: right;">
                        {!! Form::submit('Crear Tipo de Equipo', ['class' => 'btn-success rounded text-white px-3 py-1 text-base mx-1 float-rigth align-baseline']) !!}
                        <a href= "{{route('tipo.index')}}" style = "height:35px;" class="btn-warning rounded text-white px-3 py-1 text-base float-right">Cancelar</a>
                    </div>
                </td>
            </tr>
        </table>
    {!! Form::close() !!}
    
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="{{ asset('css/admin/body.css') }}">
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
    <style>
        .sidebar-dark-primary{
            background: #5f2167 !important;
            }
        .brand-link{
            background: #5f2167 !important;
            }
    </style>
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/tipo/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Tipo de Equipo')


@section('content_header')
    <h1>Editar Tipo de Equipo #{{$tiporium->id}}</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">

        {!! Form::model($tiporium,['route' => ['tipo.update', $tiporium],'autocomplete' => 'off','files' => true, 'method' => 'put']) !!}
            @include('tipo.partials.form')
            <table style="margin: 0; auto; width:100%">
                <tr>
                    <td style="display: flex; justify-content: right;">
                        <div class="d-flex justify-content-end m-0 p-0 align-self-end" >
                            @can('tipo.update')
                                {!! Form::submit('Guardar Cambios', ['name' => 'btn-update','class' => 'btn-success rounded text-white px-3 py-1 text-base mx-1 float-rigth align-baseline']) !!}
                            @endcan
                            <a href="{{route('tipo.show', $tiporium)}}" class="btn btn-info rounded text-white px-3 text-base mx-1 float-rigth align-baseline">Cancelar</a>
                        </div>
                    </td>
                </tr>
            </table>
        {!! Form::close() !!}

        
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="{{ asset('css/admin/body.css') }}">
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
    <style>
        .sidebar-dark-primary{
            background: #5f2167 !important;
            }
        .brand-link{
            background: #5f2167 !important;
            }
    </style>
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/tipo/index.blade.php
@extends('adminlte::page')

@section('title', 'Tipos de Equipo')

@section('content_header')
    @can('tipo.create')
        <a href="{{route('tipo.create')}}" style = "height: 40px;" class="btn-info rounded text-white px-3 py-2 text-base float-right">Nuevo Tipo de Equipo</a>
    @endcan
    <h1>Listado de Tipos de Equipo</h1>
@stop

@section('content')
    @if (session('info'))
            <div class="alert alert-success">
                <strong>{{ session('info') }}</strong>
            </div>
        @endif
     <div class="card">
        @if ($tips->count())
        <div class="card-body">
            <table class="table table-striped text-sm"   style="margin: 0; auto;" cellspacing="0" cellpadding="0">
                <thead style="padding:1px; background-color:#5f2167; color:white">
                        <th >#</th>
                        <th >Tipo</th>
                        <th colspan="2"></th>
                </thead>
                <tbody>
                    @foreach ($tips as $tipo)
                        <tr>
                            <td> {{ $tipo -> id }} </td>
                            <td> {{ $tipo -> tipo }} </td>
                            <td width="10px">
                                @can('tipo.show')
                                    <a href= "{{route('tipo.show',$tipo->id)}}" style="width:150px" class="btn btn-primary">Ver Tipo</a>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer" >
            {{ $tips->links() }}
        </div>
        <div>
            @push('scripts')
                <script>
                    Livewire.restart();
                </script>
            @endpush
        </div>
        @else
            <strong>No hay ningun Tipo...</strong>
        @endif
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="{{ asset('css/admin/body.css') }}">
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
    <style>
        .sidebar-dark-primary{
            background: #5f2167 !important;
            }
        .brand-link{
            background: #5f2167 !important;
            }
    </style>
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/tipo/show.blade.php
@extends('adminlte::page')

@section('title', 'Ver Tipo de Equipo')

@section('content_header')
<div class="container-fluid" style="width:100%;">
    <div class="row">
        <div class="co w-75">
            <h2 style="color:#5f2167">
                Tipo de Equipo #{{$tiporium -> id}}
            </h2>
        </div>
        <div class="col align-self-end w-75">
            <div class="d-flex justify-content-end m-0 p-0 align-self-end co" >
                @can('tipo.edit')
                    <a href= "{{route('tipo.edit',$tiporium)}}" class="btn-primary rounded text-white px-3 py-2 mx-1 text-base float-right">Editar Tipo de Equipo</a>
                @endcan

                @can('tipo.destroy')
                    <form action="{{route('tipo.destroy',$tiporium)}}" class="formulario-eliminar-tipo" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn-danger rounded text-white px-3 py-2 mx-1 text-base float-right">Eliminar Tipo de Equipo</a>
                    </form>
                @endcan
                
                
            </div>
        </div>
    </div>
</div>
@stop

@section('content')
    @if (session('info'))
        <div class="alert alert-success">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif
    
    <div class="card">
        <div class="card-body">

            <div class="row" >
                <div class="col">
                    <div class="stl_body">
                        <div class="row" >
                            <div class="co w-100">
                                <h5 style="color:#5f2167; text-transform: uppercase">
                                    DESCRIPCIÓN
                                </h5>
                            </div>
                        </div>
                        <hr class="mt-1 mb-1"/>

                        <div class="row" >
                            <div class="co w-100">
                                <h5 class="text-info">
                                    {!!$tiporium->tipo!!}
                                </h5>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <hr class="mt-1 mb-1"/>

            <div style="display: flex; justify-content: right;">
                <div class="d-flex justify-content-end m-0 p-0 align-self-end">
                        <a href= "{{route('tipo.index')}}" class="btn-info rounded text-white px-3 py-1 text-base mx-1 float-rigth align-baseline">Volver</a>
                </div>
            </div>

        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="{{ asset('css/admin/body.css') }}">
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
    <style>
        .sidebar-dark-primary{
            background: #5f2167 !important;
            }
        .brand-link{
            background: #5f2167 !important;
            }
    </style>
@stop

@section('js')
    <script> console.log('Hi!'); </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        $('.formulario-eliminar-tipo').submit(function(e){
            e.preventDefault();
        Swal.fire({
                    title: "¿Estás seguro?",
                    text: "Se eliminará la tipo.!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Si, eliminar",
                    cancelButtonText: "Cancelar"
                }).then((result) => {
                    if (result.isConfirmed) {
                        this.submit();
                    } else{
                        return false;
                    }
                });
        });
    </script>
@stop